// manifest.json is generated by python/99-generate_manifest.py and imported at
// build time (the app is a static export, so the file is known at build).
// Regenerate the manifest before building if data years change.
import manifest from "../../public/data/manifest.json";

interface YearRange {
  years: number[];
  min: number;
  max: number;
  default: number;
  fusionYears?: number[];  // Years with secretariat sub-entity breakdown
}

interface YearRanges {
  donors: YearRange;
  entityRevenue: YearRange;
  entitySpending: YearRange & { fusionYears?: number[] };
  countryExpenses: YearRange;
  sdgExpenses: YearRange;
  secretariat: YearRange;
}

const YEAR_RANGES = manifest as YearRanges;

export function useYearRanges(): YearRanges {
  return YEAR_RANGES;
}

export function generateYearRange(min: number, max: number): number[] {
  const years: number[] = [];
  for (let year = min; year <= max; year++) {
    years.push(year);
  }
  return years;
}
